version: '3'
services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
      args:
        - TRAVIS_BRANCH
    image: crypto_client
    container_name: crypto_client
    links:
      - "server:crypto-server"
    ports:
      - 80:80
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    image: crypto_server
    container_name: crypto_api
    environment:
      NODE_ENV: production
    ports:
      - 3000:80
networks:
  default:
    external:
      name: ${COMPOSE_ENV-dev1}
