version: '3'
services:
  client:
    build:
      dockerfile: ./client/Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
  server:
    environment:
      NODE_ENV: development
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
